### ISSUE TITLE
Client directory empty

### ISSUE THREAD

**Issue by el-guero-mero** [beckiDev/urlshertmer#1]
Hello Becki!

I can start the JSON server, but there is no UI to run so far as I can tell. I see here in the repo that the /client directory is empty, but I suspect I may need files there to run the UI. Can you please let me know what needs to happen to troubleshoot?

Thank you,

Mateo

**Comment by beckiDev** [comment]
Hi Mateo,

Im sorry I forgot to add more notes into Readme.
Please cd client and then npm install as well

Then run from uper directory run npm run dev

Best Regards,
Becki

**Comment by el-guero-mero** [comment]
What URL do I navigate to once I've started the app?

**Comment by beckiDev** [comment]
Localhost:3000

**Comment by el-guero-mero** [comment]
There are no contents in the /client directory in the repo that I can see. Can you please check that the files in the /client directory are also pushed to the repo recursively? Also, when I try to run "npm run dev" I get an error of missing script: start. 

Many thanks!

**Comment by beckiDev** [comment]
Hi Mateo,
I’m sorry that it took me that much time to figure out 
This is new url:
https://github.com/beckiDev/urlShort/tree/master/client <https://github.com/beckiDev/urlShort/tree/master/client>
After installation page localhost:3000 will; be open automatically 
Best Regards,
Becki
